---
- name: setup user
  user:
    name: "{{ setup_user }}"

- name: network utils
  apt:
    name: "{{ item }}"
    install_recommends: no
    state: present
  with_items:
    - nmap
    - traceroute
    - iperf
