- set_fact:
    provisioning_command: >
      docker exec -ti '{{ container_name }}'
      ansible-playbook -i /provisioning/{{ inventory }}.hosts
      /provisioning/{{ playbook }}.yml
      -e 'domain_postfix={{ domain_postfix }}'

- name: provisioning command for {{ container_name }}
  debug:
    msg: "{{ provisioning_command }}"

- name: provision {{ container_name }} container (may take few minutes)
  command: "{{ provisioning_command }}"
  register: res
  failed_when: no

- name: provisioning results for {{ container_name }}
  debug:
    msg: "RETURN CODE: {{ res.rc }}"

- name: stdout for {{ container_name }}
  debug:
    msg: "STDOUT: {{ res.stdout }}"
  when: res.stdout is defined

- name: stderr for {{ container_name }}
  debug:
    msg: "STDERR: {{ res.stderr }}"
  when: res.stderr is defined

- name: provisioning fail?
  fail: msg="unable to provision  {{ container_name }} container"
  when: "res.rc != 0 or 'skipping: no hosts matched' in res.stdout"

