- include: ../../../tasks/update_repo.yml
  vars:
    dir: scala.moscow
    repo: https://github.com/scala-moscow/scala.moscow.git
  tags:
    - update_repos

- include: ../../../tasks/sync_provisioning.yml

- name: generate inventory file
  template:
    dest: "{{ files_dir }}/provisioning/provision_{{ container.fqn }}.hosts"
    src: "{{ item }}"
    owner: "{{ setup_user }}"
  with_first_found:
    - "{{ container.name }}_container_inventory.j2"
    - ../../../templates/container_inventory.j2

- include: ../../../tasks/run_playbook_in_container.yml
  vars:
    container_name: "{{ container.fqn }}"
    inventory: provision_{{ container.fqn }}
    playbook: setup_{{ container.name }}_container
