- name: build image
  debug:
    msg: "name={{ image.name }} version={{ image.version }}"
  changed_when: no

- include: ../../../tasks/detect_docker_image_id.yml
  vars:
    image_mask: "{{ docker_container_ns }}/{{ image.name }}|{{ image.version }}"

- name: "{{ image.name }} image_id"
  debug:
    msg: "image_id = {{ image_id|default('[not exists]') }}"
  changed_when: no

- name: "{{ image.name }} image docker build dir"
  file:
    state: directory
    path: "{{ files_dir }}/dockerfiles/{{ image.name }}"
    mode: 0775
    owner: "{{ setup_user }}"
    group: "{{ docker_group }}"
  when: image_id == ''

- name: "{{ image.name }} image dockerfile"
  template:
    dest: "{{ files_dir }}/dockerfiles/{{ image.name }}/Dockerfile"
    owner: "{{ setup_user }}"
    group: "{{ docker_group }}"
    src: dockerfiles/{{ image.name }}.j2
  when: image_id == ''

- include: ../../../tasks/sync_provisioning.yml
  when: image_id == ''

- name: generate inventory file
  template:
    dest: "{{ files_dir }}/provisioning/build_{{ image.name }}_{{ image.version }}.hosts"
    src: image_inventory.j2
    owner: "{{ setup_user }}"
  when: image_id == ''

- name: build {{ image.name }} pre provisioning image (may take few minutes)
  docker_image:
    name: "{{ docker_container_ns }}/{{ image.name }}_pre"
    tag: "{{ image.version }}"
    path: "{{ files_dir }}/dockerfiles/{{ image.name }}"
  when: image_id == ''

- name: delete {{ image.name }} build container
  docker:
    name: build_{{ image.name }}_{{ image.version }}
    state: absent
    image: "{{ docker_container_ns }}/{{ image.name }}_pre:{{ image.version }}"
  when: image_id == ''

- name: start temp {{ image.name }} build container
  docker:
    name: build_{{ image.name }}_{{ image.version }}
    state: running
    image: "{{ docker_container_ns }}/{{ image.name }}_pre:{{ image.version }}"
    volumes: "{{ files_dir }}/provisioning:/provisioning:ro"

  when: image_id == ''

- name: provisioning command
  debug:
    msg: >
      docker exec -ti build_{{ image.name }}_{{ image.version }}
      ansible-playbook -i /provisioning/build_{{ image.name }}_{{ image.version }}.hosts
      /provisioning/setup_{{ image.name }}.yml -e 'domain_postfix={{ domain_postfix }}'
  when: image_id == ''

- include: ../../../tasks/run_playbook_in_container.yml
  vars:
    container_name: build_{{ image.name }}_{{ image.version }}
    inventory: build_{{ image.name }}_{{ image.version }}
    playbook: setup_{{ image.name }}
  when: image_id == ''
  tags:
    - temp
    - image_provisioning

- name: stop temp {{ image.name }} build container
  docker:
    name: build_{{ image.name }}_{{ image.version }}
    state: stopped
    image: "{{ docker_container_ns }}/{{ image.name }}_pre:{{ image.version }}"
  when: image_id == ''
  tags:
    - temp

- name: commit {{ image.name }} image
  command: >
    docker commit build_{{ image.name }}_{{ image.version }}
    {{ docker_container_ns }}/{{ image.name }}:{{ image.version }}
  when: image_id == ''
  tags:
    - temp
    - image_provisioning

- name: delete {{ image.name }} build container
  docker:
    name: build_{{ image.name }}_{{ image.version }}
    state: absent
    image: "{{ docker_container_ns }}/{{ image.name }}_pre:{{ image.version }}"
  when: image_id == ''
  tags:
    - temp
  ignore_errors: yes

- name: delete temp {{ image.name }} image
  command: docker rmi -f {{ docker_container_ns }}/{{ image.name }}_pre:{{ image.version }}
  when: image_id == ''
  tags:
    - temp
  ignore_errors: yes
