- name: build image
  debug:
    msg: "name={{ image.name }} version={{ image.version }}"
  changed_when: no

- include: ../../../tasks/detect_docker_image_id.yml
  vars:
    image_mask: "{{ docker_container_ns }}/{{ image.name }}|{{ image.version }}"

- name: "{{ image.name }} image_id"
  debug:
    msg: "image_id = {{ image_id|default('[not exists]') }}"
  changed_when: no

- set_fact:
    docker_build_dir: "{{ files_dir }}/dockerfiles/{{ image.name }}"
    image_inventory_name: build_{{ image.name }}_{{ image.version }}
    pre_image_name: "{{ docker_container_ns }}/{{ image.name }}_pre"
    build_container_name: build_{{ image.name }}_{{ image.version }}
  when: image_id == ''

- set_fact:
    docker_file: "{{ docker_build_dir }}/Dockerfile"
    image_inventory_file: provisioning/{{ image_inventory_name }}.hosts
    pre_image_fqn: "{{ pre_image_name }}:{{ image.version }}"
  when: image_id == ''


- name: "{{ image.name }} image docker build dir"
  file:
    state: directory
    path: "{{ docker_build_dir }}"
    mode: 0775
    owner: "{{ setup_user }}"
    group: "{{ docker_group }}"
  when: image_id == ''

- name: "{{ image.name }} image dockerfile"
  template:
    dest: "{{ docker_file }}"
    owner: "{{ setup_user }}"
    group: "{{ docker_group }}"
    src: dockerfiles/{{ image.name }}.j2
  when: image_id == ''

- include: ../../../tasks/sync_provisioning.yml
  when: image_id == ''

- name: generate inventory file
  template:
    dest: "{{ files_dir }}/{{ image_inventory_file }}"
    src: image_inventory.j2
    owner: "{{ setup_user }}"
  when: image_id == ''

- name: build {{ image.name }} pre provisioning image (may take few minutes)
  docker_image:
    name: "{{ pre_image_name }}"
    tag: "{{ image.version }}"
    path: "{{ docker_build_dir }}"
  when: image_id == ''

- name: delete {{ image.name }} build container
  docker:
    name: "{{ build_container_name }}"
    state: absent
    image: "{{ pre_image_fqn }}"
  when: image_id == ''

- name: start temp {{ image.name }} build container
  docker:
    name: "{{ build_container_name }}"
    state: running
    image: "{{ pre_image_fqn }}"
    volumes: "{{ files_dir }}/provisioning:/provisioning:ro"

  when: image_id == ''

- include: ../../../tasks/run_playbook_in_container.yml
  vars:
    container_name: "{{ build_container_name }}"
    inventory: "{{ image_inventory_name }}"
    playbook: setup_{{ image.name }}
  when: image_id == ''
  tags:
    - image_provisioning

- name: stop {{ image.name }} build container
  docker:
    name: "{{ build_container_name }}"
    state: stopped
    image: "{{ pre_image_fqn }}"
  when: image_id == ''
  tags:
    - image_provisioning

- name: commit {{ image.name }} image
  command: >
    docker commit '{{ build_container_name }}'
    '{{ docker_container_ns }}/{{ image.name }}:{{ image.version }}'
  when: image_id == ''
  tags:
    - image_provisioning

- name: delete {{ image.name }} build container
  docker:
    name: "{{ build_container_name }}"
    state: absent
    image: "{{ pre_image_fqn }}"
  when: image_id == ''
  ignore_errors: yes

- name: delete temp {{ image.name }} image
  command: docker rmi '{{ pre_image_fqn }}'
  when: image_id == ''
  ignore_errors: yes
